import { execFileSync } from 'node:child_process'
import { existsSync, readdirSync } from 'node:fs'
import { join, relative } from 'node:path'

const git = (cwd, args) => {
  try {
    return execFileSync('git', ['-C', cwd, ...args], {
      encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'],
    }).trim()
  } catch { return null }
}

const orgOf = (url) => {
  const m = url?.match(/[:/]([^/:]+)\/[^/]+?(\.git)?$/)
  return m ? m[1] : null
}

/**
 * Walk `root` (one level deep, plus one nested level) looking for git
 * checkouts, and work out each one's org and most plausible live branch.
 * This is what makes `init --scan` a zero-typing setup on a fresh machine.
 */
export function scanWorkspace(root, { depth = 2 } = {}) {
  const found = []

  const visit = (dir, level) => {
    let entries
    try {
      entries = readdirSync(dir, { withFileTypes: true })
    } catch { return }
    for (const e of entries) {
      if (!e.isDirectory() || e.name.startsWith('.') || e.name === 'node_modules') continue
      const path = join(dir, e.name)
      const isRepo = existsSync(join(path, '.git'))
      if (isRepo) {
        const repo = inspect(path, root)
        if (repo) found.push(repo)
      }
      // descend even into a repo — people keep sibling checkouts inside one
      if (level < depth) visit(path, level + 1)
    }
  }
  visit(root, 1)

  // same repo checked out twice — keep the one with the most recent commit
  const best = new Map()
  for (const r of found) {
    const prev = best.get(r.name)
    if (!prev || (r.lastCommit || '') > (prev.lastCommit || '')) best.set(r.name, r)
  }
  return [...best.values()].sort((a, b) => (b.lastCommit || '').localeCompare(a.lastCommit || ''))
}

const CONVENTIONAL = ['main', 'master', 'production', 'prod', 'live', 'release']

/**
 * The live branch is whichever remote branch has the newest commit — a repo
 * whose `main` went stale because the team moved to another branch would
 * otherwise look dead. Conventional names win ties (and near-ties), so an
 * active `main` is never displaced by a busier feature branch.
 */
function liveBranch(path, preferred, remotes) {
  const order = [preferred, ...remotes.filter((r) => r !== preferred)]
  const refs = []
  for (const remote of order) {
    const out = git(path, [
      'for-each-ref', `refs/remotes/${remote}`,
      '--format=%(refname:short)\t%(committerdate:short)',
    ])
    if (!out) continue
    for (const line of out.split('\n').filter(Boolean)) {
      const [ref, date] = line.split('\t')
      if (ref.endsWith('/HEAD') || !ref.includes('/')) continue
      const short = ref.split('/').slice(1).join('/')
      refs.push({ ref, date, remote, conventional: CONVENTIONAL.includes(short) })
    }
  }
  if (!refs.length) return null

  refs.sort((a, b) => b.date.localeCompare(a.date))
  const newest = refs[0]
  // A conventional branch that is merely *behind* the newest branch is still
  // the trunk — teams merge to main in bursts. Only when main has gone truly
  // cold (half a year) do we conclude the team moved elsewhere.
  const cutoff = daysBefore(newest.date, 180)
  const trunk = refs.find((r) => r.conventional && r.date >= cutoff)
  return (trunk || newest).ref
}

const daysBefore = (date, days) => {
  const d = new Date(`${date}T00:00:00Z`)
  d.setUTCDate(d.getUTCDate() - days)
  return d.toISOString().slice(0, 10)
}

function inspect(path, root) {
  const remotes = git(path, ['remote'])?.split('\n').filter(Boolean) || []
  if (!remotes.length) return null

  const urlOf = (r) => git(path, ['remote', 'get-url', r])
  // upstream wins (on a fork it is the company repo), then origin. A personal
  // fork remote must never decide the repo's identity.
  const preferred = ['upstream', 'origin'].find((r) => remotes.includes(r)) || remotes[0]
  const url = urlOf(preferred)
  const name = url?.match(/([^/:]+?)(\.git)?$/)?.[1]
  if (!name) return null

  const branch = liveBranch(path, preferred, remotes)
  if (!branch) return null

  return {
    name,
    org: orgOf(url),
    branch,
    path,
    relPath: relative(root, path) || '.',
    lastCommit: git(path, ['log', branch, '-1', '--date=short-local', '--format=%cd']),
  }
}

/** Turn scan results into a config object, keeping only recently active repos. */
export function configFromScan(repos, { root, activeSince, org }) {
  const kept = repos
    .filter((r) => !org || r.org === org)
    .filter((r) => !activeSince || (r.lastCommit || '') >= activeSince)

  const orgs = [...new Set(kept.map((r) => r.org).filter(Boolean))]
  const branches = kept.map((r) => r.branch)
  const commonBranch = mode(branches) || 'origin/main'

  return {
    '//': 'Generated by `whatshipped init --scan`. searchPaths/cloneInto are relative to "workspace".',
    org: orgs.length === 1 ? orgs[0] : (org || orgs[0] || null),
    defaultBranch: commonBranch,
    workspace: tildify(root),
    searchPaths: [...new Set(kept.map((r) => dirOf(r.relPath)))].sort(),
    cloneInto: dirOf(kept[0]?.relPath || '.'),
    repos: kept.map((r) => (r.branch === commonBranch
      ? { name: r.name }
      : { name: r.name, branch: r.branch })),
  }
}

/** Keep generated configs readable (and portable between users' homes). */
const tildify = (p) => {
  const home = process.env.HOME || ''
  return home && p.startsWith(home) ? `~${p.slice(home.length)}` : p
}

const dirOf = (rel) => {
  const parts = rel.split('/')
  return parts.length > 1 ? parts.slice(0, -1).join('/') : '.'
}

const mode = (arr) => {
  const counts = new Map()
  for (const v of arr) counts.set(v, (counts.get(v) || 0) + 1)
  return [...counts.entries()].sort((a, b) => b[1] - a[1])[0]?.[0]
}
